df=read.table("household_power_consumption.txt",sep=";",header=TRUE)
xf=subset(df,Date=="2007-02-01" | Date=="2007-02-02")
df$Date=dmy(df$Date)
xf=subset(df,Date=="2007-02-01" | Date=="2007-02-02")
xf[,5]=as.numeric(as.character(xf[,5]))
xf[,6]=as.numeric(as.character(xf[,6]))
xf[,7]=as.numeric(as.character(xf[,7]))
xf[,8]=as.numeric(as.character(xf[,8]))
xf[,3]=as.numeric(as.character(xf[,3]))
xf[,4]=as.numeric(as.character(xf[,4]))
a=as.character(xf[,1])
b=paste(a,xf[,2])
xf$datetime=(strptime(b,"%Y-%m-%d %H:%M:%S"))


par(mfrow=c(2,2),mar=c(4,4,2,2))
plot(xf$datetime,xf$Global_active_power,"l",ylab="Global Active Power",xlab="")
plot(xf$datetime,xf$Voltage,xlab="datetime",ylab="Voltage","l")
plot(xf$datetime,xf$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
lines(xf$datetime,xf$Sub_metering_1)
lines(xf$datetime,xf$Sub_metering_2,col="red")
lines(xf$datetime,xf$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1,1),cex=0.5,bty="n")
plot(xf$datetime,xf$Global_reactive_power,xlab="datetime",ylab="Global_reactive_power","l")

dev.copy(png,"plot4.png")
dev.off()

